### ISSUE TITLE
Website or standalone GitHub repo?

### ISSUE THREAD

**Issue by pelmer** [iris-hep/analysis-connections#1]
Hi Jim, should this be something we put on the website itself rather than a separate standalone GitHub repo?

**Comment by pelmer** [comment]
Never mind, I understand better what this is now that I have caught up in Slack!

**Comment by jpivarski** [comment]
In a way, it is on the website, because its URL is within the iris-hep.org domain. That's why I wanted to go slowly with this, hoping the fact that it's not linked from any other pages would excuse its incompleteness.

I half considered adding a page to the main website repo, but that would require us to run Jekyll, possibly breaking something else, just to see the applet. When we're ready to go "live" (more than currently), we could merge it into the main repo for centralized tracking of changes.
